version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # ports:
    #   - "80:80" # Expose port 80
    env_file:
      - ./frontend/.env
    volumes:
      - frontend_node_modules:/app/node_modules

  backend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    command: ["npm", "run", "serve"]

  email-worker:
    build:
      context: ./backend
      dockerfile: email.worker.dockerfile
    restart: always
    env_file:
      - backend/.env
    command: ["npm", "run", "emailWorker"]

  db-worker:
    build:
      context: ./backend
      dockerfile: db.worker.dockerfile
    restart: always
    env_file:
      - backend/.env
    command: ["npm", "run", "dbWorker"]

  cronjob:
    build:
      context: ./backend
      dockerfile: cronjob.dockerfile
    restart: always
    env_file:
      - backend/.env
    command: ["npm", "run", "cronJob"]

volumes:
  frontend_node_modules:
  backend_node_modules:
